# For more information: https://laravel.com/docs/sail
version: '3'
services:
    apisoftcent.test:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: palash7862/apisoftcent
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - apisoftcent
networks:
    apisoftcent:
        driver: bridge
# volumes:
